

title: Font Family Variables
email: d
description: Hi
baseurl: "/font-family" 
url: "" 
twitter_username: d
github_username:  d
destination: docs

# Build settings

plugins:
  - jekyll-feed

#
exclude:
  - docs
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
